### ISSUE TITLE
not working on my rig sadly

### ISSUE THREAD

**Issue by thekillerwave** [NarutoUA/gta5_fsr#3]
I did everything you said like putting the files next to the game's .exe and tried to turn on FSR by putting the frame scaling mode to 0.5x and it was just the normal mode. Even after that i tried to to turning it on by tapping the button F3. nothing. 

i have one question, how did you get your hands on FSR? i tought it was exclusive for limited time before being open source. 

my PC specs:
AMD ryzen 5 2500u 4 cores / 8 threads 2Ghz
AMD Radeon rx 560x 4GB
MICRON 16 DDR4 2400mhz dual channel
SSD Hynix 128GB / WD 1TB 5400tr/mins
180 watt power supply

Tank you for taking your time to read my comments.

**Comment by NarutoUA** [comment]
Should be fixed in 1.0.2
Please reply if it works

**Comment by thekillerwave** [comment]
No need to mention it, i will, i'm really interested in your work

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by thekillerwave** [comment]
Well it's still not working, i've done the exact same things as before and nothing happenned
